# Generated by Django 5.1.3 on 2025-02-03 10:50

import cloudinary.models
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Seller',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='image')),
                ('company_name', models.CharField(max_length=100)),
                ('street_name', models.CharField(max_length=200)),
                ('postal_code', models.CharField(max_length=10)),
                ('district', models.CharField(choices=[('barguna', 'Barguna'), ('barisal', 'Barisal'), ('bhola', 'Bhola'), ('jhalokati', 'Jhalokati'), ('patuakhali', 'Patuakhali'), ('pirojpur', 'Pirojpur'), ('bandarban', 'Bandarban'), ('brahmanbaria', 'Brahmanbaria'), ('chandpur', 'Chandpur'), ('chattogram', 'Chattogram'), ('coxsbazar', "Cox's Bazar"), ('cumilla', 'Cumilla'), ('feni', 'Feni'), ('khagrachari', 'Khagrachari'), ('lakshmipur', 'Lakshmipur'), ('noakhali', 'Noakhali'), ('rangamati', 'Rangamati'), ('dhaka', 'Dhaka'), ('faridpur', 'Faridpur'), ('gazipur', 'Gazipur'), ('gopalganj', 'Gopalganj'), ('kishoreganj', 'Kishoreganj'), ('madaripur', 'Madaripur'), ('manikganj', 'Manikganj'), ('munshiganj', 'Munshiganj'), ('narayanganj', 'Narayanganj'), ('narsingdi', 'Narsingdi'), ('rajbari', 'Rajbari'), ('shariatpur', 'Shariatpur'), ('tangail', 'Tangail'), ('bagerhat', 'Bagerhat'), ('chuadanga', 'Chuadanga'), ('jashore', 'Jashore'), ('jhenaidah', 'Jhenaidah'), ('khulna', 'Khulna'), ('kushtia', 'Kushtia'), ('magura', 'Magura'), ('meherpur', 'Meherpur'), ('narail', 'Narail'), ('satkhira', 'Satkhira'), ('bogura', 'Bogura'), ('chapainawabganj', 'Chapainawabganj'), ('joypurhat', 'Joypurhat'), ('naogaon', 'Naogaon'), ('natore', 'Natore'), ('pabna', 'Pabna'), ('rajshahi', 'Rajshahi'), ('sirajganj', 'Sirajganj'), ('dinajpur', 'Dinajpur'), ('gaibandha', 'Gaibandha'), ('kurigram', 'Kurigram'), ('lalmonirhat', 'Lalmonirhat'), ('nilphamari', 'Nilphamari'), ('panchagarh', 'Panchagarh'), ('rangpur', 'Rangpur'), ('thakurgaon', 'Thakurgaon'), ('habiganj', 'Habiganj'), ('maulvibazar', 'Maulvibazar'), ('sunamganj', 'Sunamganj'), ('sylhet', 'Sylhet')], default='Dhaka', max_length=100)),
                ('mobile_no', models.CharField(max_length=12, unique=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.CharField(choices=[('⭐', '⭐'), ('⭐⭐', '⭐⭐'), ('⭐⭐⭐', '⭐⭐⭐'), ('⭐⭐⭐⭐', '⭐⭐⭐⭐'), ('⭐⭐⭐⭐⭐', '⭐⭐⭐⭐⭐')], max_length=10)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('seller', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='seller.seller')),
            ],
        ),
    ]
